apiVersion: v1
kind: PersistentVolume
metadata:
  name: api-map-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /var/lib/docker/volumes/api-map/_data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: api-map-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 1Gi
